### PR TITLE
Use jit ops

### PR DESCRIPTION
**Pull request by skeydan**

### CODE REVIEW

**Review by dfalbel — COMMENTED** [review]
Do you want to add one simple test just to recover CI? Maybe it could list the ops in torch_sparse namespace from jit?

**Comment by skeydan** [comment]
Makes sense! Done!

**Review by dfalbel — APPROVED** [review]
Looks good. CI is broken, but as discussed, not sure if it's worth recovering...

**Comment by skeydan** [comment]
Yeah, I guess it's not worth spending the time ... So just in case you happen to know why one Windows test fails, while the other doesn't, and one just stays queued, could you tell me?
Otherwise, should I merge?

**Comment by dfalbel** [comment]
Yes, feel free to merge.

**Pull request merged**
